export default {
  logoHeader: require("./media/logos/HeaderLogo.png"),
  iconLogin: require("./media/images/login-image.png"),
  iconChangeDroner: require("./media/images/iconChangDrone.png"),
  iconChangeTime: require("./media/images/changeTime.png"),
  iconReviewDroner: require("./media/images/reviewDroner.png"),
  iconExtend: require("./media/images/extend.png"),
  iconTime: require("./media/images/time.png"),
  pointActive: require("./media/images/pointactive.png"),
  pointDrafting: require("./media/images/pointdrafting.png"),
  pointDisabled: require("./media/images/pointdisabled.png"),
  adminlogo: require("./media/images/adminlogo.png"),
  iconcopy: require("./media/images/copy.png"),
  icondelete: require("./media/images/delete.png"),
};
