export default {
  logoHeader: require("./media/logos/HeaderLogo.png"),
  iconLogin: require("./media/images/login-image.png"),
  iconChangeDroner: require("./media/images/iconChangDrone.png"),
  iconChangeTime: require("./media/images/changeTime.png"),
  iconReviewDroner: require("./media/images/reviewDroner.png"),
  iconExtend: require("./media/images/extend.png"),
  iconTime: require("./media/images/time.png"),
  pointActive: require("./media/images/pointactive.png"),
  pointDrafting: require("./media/images/pointdrafting.png"),
  pointDisabled: require("./media/images/pointdisabled.png"),
  pointWarning: require("./media/images/pointwarning.png"),
  adminlogo: require("./media/images/adminlogo.png"),
  iconcopy: require("./media/images/copy.png"),
  icondelete: require("./media/images/delete.png"),
  injection: require("./media/images/injectionicon.png"),
  drug: require("./media/images/drugicon.png"),
  arrowUp: require("./media/images/arrowUp.png"),
  arrowDown: require("./media/images/arrowDown.png"),
  arrowGreen: require("./media/images/arraow-green.png"),
  inforedeem: require("./media/images/info-redeem.png"),
  coinFarmer: require("./media/images/coin.png"),
  coinDroner: require("./media/images/coinDroner.png"),
  iconQuotaReport: require("./media/images/icon-quota-report.png"),
  arrowReport: require("./media/images/arrowReport.png"),
  coin: require("./media/images/coin.png"),
  pointRankActive: require("./media/images/point-rank-active.png"),
  pointRankInActive: require("./media/images/point-rank-inactive.png"),
  targetActive: require("./media/images/target-active.png"),
  targetInActive: require("./media/images/target-inactive.png"),
  quotaReport: require("./media/images/quotaReport_inactive.png"),
  arrowDownWhite : require('./media/images/arrow_down_white.png')

};
